-- 0192 — 04q: Report Semanal Executivo (camada de dados).
--
-- Corpo canônico das funções em `supabase_migrations.schema_migrations`, pelo nome de cada
-- migração abaixo; `supabase db pull` reconcilia este arquivo.
--
--   reports_estrutura
--     `report_config` (uma linha por tipo — dois agendamentos do mesmo report seriam dois
--     e-mails iguais), `report_execucoes` (com o SNAPSHOT em `dados`, para um report de
--     três meses atrás abrir com os números daquela época) e `report_series`.
--
--     `app_report_gestor()`: tem o módulo Comercial e NÃO é vendedor. `app_gestor_comercial()`
--     não servia — é "perfil Admin ou Comercial", e a auxiliar do closer tem perfil
--     Comercial. O report mostra a carteira inteira e o desempenho de cada pessoa.
--
--   reports_materializar_series
--     Job diário. `peso` existe porque média de média não é média: o prazo médio de um
--     trimestre não é a média dos três prazos mensais. Reescreve a janela em vez de fazer
--     upsert — uma antecipação pode converter, regredir e converter de novo.
--
--   reports_regua_de_tres_janelas
--     `app__rp_serie` e `app__rp_indicador`. A DECISÃO que define se o report mente: a
--     média é sobre os meses QUE TÊM DADO, não sobre doze de calendário. A operação começou
--     em 20/07/2026 — dividir por doze diluiria tudo por nove meses em que a empresa não
--     existia, e toda semana apareceria como "180% acima da média".
--     `subir_e_pior` viaja no indicador: metade deles é ruim quando cresce.
--
--   reports_bloco_operacao                  blocos 1, 3 e 4
--   reports_bloco_comercial_credito_time    blocos 2, 5, 6 e 10
--   reports_bloco_carteira_certificados_atencao   blocos 7, 8, 9 e 11
--
--     Tempo de esteira só sobre análises que NASCERAM aqui: 84 das 87 vieram do backfill da
--     Atradius com a decisão datada de ANTES do registro, e a média sobre a base inteira
--     dava −152 dias.
--
--   reports_certificado_invisivel_calibrado
--   reports_certificado_invisivel_por_grupo
--   reports_certificado_invisivel_agrupa_por_conta
--     O "quanto está invisível" em três correções sucessivas, cada uma medida:
--       `faturamento/12` dava R$ 2,36 BI/mês — o certificado mostra o CUSTO do cliente com
--       fornecedores, não a receita dele. A razão real, medida nos 16 CNPJs que têm
--       certificado, é 0,1011 (p25 0,044 · p75 0,207).
--       Somar matriz + SPEs contava o mesmo grupo quarenta vezes.
--       A chave do grupo é `empresa_id`, e não a raiz do CNPJ: a COSAMPA tem quatro raízes
--       na mesma conta, e agrupar por raiz a repetia quatro vezes na lista.
--       O total é o dos N MAIORES, e o campo se chama `total_mes_do_topo`: extrapolar 16
--       observações para 600 grupos dava R$ 1,37 bi/mês, cem vezes o que a operação inteira
--       converte — e um total impossível destrói a credibilidade da página inteira.
--
--   reports_snapshot_semanal
--     `app__rp_montar` (mecânica, sem sessão, para o worker) + `app_report_semanal`
--     (autorizada). A aba, o PDF e o e-mail consomem esta estrutura e nenhum recalcula.
--
--   reports_bucket_semanais
--     Bucket privado `reports-semanais`, separado de `report-anexos` (que é dos anexos de
--     BUG REPORT — mesma palavra, domínios diferentes). Privado porque o PDF traz a
--     carteira inteira e a comissão nominal de cada vendedor, e o caminho
--     `{ano}/report-semanal-oneos-{ano}-S{semana}.pdf` não é difícil de adivinhar.
--
--   reports_janela_padrao_e_a_semana_fechada
--     A janela padrão da aba passou a ser a MESMA do PDF. Estava `current_date - 1` com
--     `date_trunc('week', ...)`, o que devolvia a semana CORRENTE parcial: num domingo
--     06/09 a aba abria em 31/08–05/09, seis dias, enquanto o worker gerava 24/08–30/08.
--     Duas réguas para "qual semana é esta" é exatamente o que o 04q §6 existe para não
--     ter. Agora é `current_date - isodow(current_date)`, a mesma aritmética de
--     `apps/worker/src/jobs/reports/janela.ts`.

--   reports_retrato_auxiliares
--   reports_certificado_invisivel_na_data
--   reports_operacao_retrato_da_janela
--   reports_comercial_retrato_da_janela
--   reports_comercial_retrato_parametrizado
--   reports_carteira_retrato_parametrizado
--   reports_montar_e_rpc_com_retrato
--   reports_retrato_carteira_em_diz_a_verdade
--   reports_carteira_em_hoje_e_a_tabela_viva
--     O REPORT PASSOU A DIZER DE QUANDO É CADA NÚMERO.
--
--     O problema: metade da estrutura era FLUXO da janela (volume, VOP, receita, operações,
--     comissão — presos por `convertida_em` e `evento_em`, e esses sempre estiveram certos)
--     e metade era ESTADO lido no instante da emissão. O PDF de 24/08–30/08 gerado em 06/09
--     imprimia a carteira de 06/09: limite ocioso de R$ 59,7 mi onde a semana 35 tinha
--     R$ 62,6 mi, 40,3% de utilização virando 43,1%, 51 antecipações travadas virando 60.
--
--     `p_retrato` é a data em que os ESTOQUES são lidos. O PDF passa `p_fim` e congela; a
--     tela passa `current_date` e fica ao vivo, que é o que se espera de uma tela. Os
--     fluxos não mudam nos dois casos — a data do evento não depende de quando se pergunta.
--
--     De onde vem o passado:
--       `clientes_onepay_snapshots` — captura diária desde 25/07/2026, 55 CNPJs, com os
--       mesmos campos da tabela viva. `app__rp_carteira_em(data)` devolve a captura mais
--       recente que não é posterior à data; HOJE ele lê a tabela viva, porque a captura é
--       de madrugada e divergia dela em R$ 500 mil — um terceiro número para a pergunta que
--       o Meu Dia já responde lendo `clientes_onepay` direto.
--
--       `funil_transicoes` — o log dos gatilhos `sdr_leads_transicao`/`vendas_transicao`.
--       "Reuniões realizadas" e "MOUs" saíam de `atualizado_em`, que é carimbo de última
--       EDIÇÃO e não data de evento: um lead tocado depois SAÍA da semana em que a reunião
--       aconteceu, e um lead velho reeditado ENTRAVA numa semana em que nada ocorreu. O log
--       começa em 30/08/2026: semanas anteriores vêm zeradas, e zero declarado é melhor que
--       um número que se reescreve a cada leitura.
--
--     Também corrigido de passagem: `certificados vencendo em 30 dias` era
--     `coberto AND expires_at < now() + 30d`, e `coberto` já exigia `> now() + 30d` — a
--     condição era uma contradição e dava zero SEMPRE. Agora é "válido em `p_retrato` e
--     expira nos 30 dias seguintes", que é a pergunta que alguém queria fazer.
--
--     E o time do ranking passou a incluir quem teve lançamento NA JANELA mesmo se hoje
--     está inativo: filtrar só por `ativo` apagava de um report antigo a comissão de quem
--     saiu depois, e comissão paga não desaparece do mês em que foi paga.
--
--     O que continua sendo de hoje, porque não existe histórico: `antecipacoes.status` e
--     `analises_credito.estagio` (a plataforma e a esteira sobrescrevem), a composição dos
--     grupos em `certificado_universo`, e `empresas.faturamento_anual` (saída do modelo do
--     04c — recalibrar o estimador muda o "invisível" para trás). Nesses casos o que a
--     linha afirma é a DATA que a colocou ali, não o rótulo que a acompanha.
--
--   reports_conversas_sem_resposta_pelo_log_de_mensagens
--     A fila "conversas aguardando resposta" saía de `conversas.ultima_direcao` e
--     `ultima_mensagem_em`, que são o estado de HOJE: quem respondeu ontem some da fila de
--     uma semana atrás em que estava esperando. A fila da semana 35 dava 0 — falso, e não
--     conservador. Agora sai de `comunicacoes_thread` (a mensagem individual, com `direcao`
--     e `criado_em`), que responde "qual era a última mensagem naquele dia". Conferido: ao
--     vivo reproduz exatamente o número da régua antiga (34). O log começa em 01/09/2026;
--     janelas anteriores seguem em zero, agora por ausência de dado e não por régua errada.
